### ISSUE TITLE
Katacoda - add feature to resize code pane

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/training-scenarios#96] opened 2019-08-28 20:59 UTC
On katacoda.com, I'd like the ability to resize the code pane. Currently, the code and example panels are hard coded to split 50/50. It's difficult to read all that code in such a small area.

**Comment by christiemolloy** [comment] 2019-09-24 14:16
@gsoria would this be a simple change to implement the resize ability?

**Comment by gsoria** [comment] 2019-10-02 14:41
Hi @christiemolloy, we will look into this and we'll back to you. What is the priority of this issue?

**Comment by christiemolloy** [comment] 2019-10-07 12:55
Thank you @gsoria, the issue isn't blocking our release, its just a usability issue, so I would say medium-low priority.

**Comment by christiemolloy** [comment] 2019-10-31 17:51
@gsoria we have had some user feedback about the frustration in not being able to re-size the window pane. It would be great to have this feature added :)

**Comment by gsoria** [comment] 2019-11-04 16:22
@christiemolloy this has been implemented :)

**Comment by christiemolloy** [comment] 2019-11-04 18:51
Thank you so much for implementing this. Would it be a lot of effort to also allow resize on the vertical axis? We have had some users speak about how it would improve the user experience if they could resize vertically (expand the instructions).

Currently, the way the panel is set up, users are expecting that they will be able to re-size vertically. 

@gsoria 

<img width="200" alt="Screen Shot 2019-11-04 at 1 44 35 PM" src="https://user-images.githubusercontent.com/20118816/68148151-6d985880-ff09-11e9-8261-3a0bd0136cbd.png">

**Comment by gsoria** [comment] 2019-11-04 20:01
@christiemolloy we are working on this, we'll update you soon :)

**Comment by gsoria** [comment] 2019-12-10 19:00
Hi @christiemolloy. Can we close this issue and left only the reported bug about it https://github.com/patternfly/training-scenarios/issues/210 Thanks!

**Comment by christiemolloy** [comment] 2019-12-12 22:12
Closing this issue

**Closed by christiemolloy** 2019-12-12 22:12 UTC
Labels: Moderate Priority, katacoda

**Comment by kmriaz** [comment] 2021-09-07 03:40
is there a ways to resize the terminal host 1 in katacoda? pls advice.
